### ISSUE TITLE
Question about the input dimension for NIR dataset

### ISSUE THREAD

**Issue by liteonalvinchuang** [LinXi1C/SSPD#1]
I saw your paper on the arXiv, nice work! Just a small question: when you train your model using the MR-NIRP dataset, do you assign the input channel dimension to be 1 (i.e., single NIR channel)? or 3 but with each channel being the same NIR frame?

**Comment by LinXi1C** [comment]
> I saw your paper on the arXiv, nice work! Just a small question: when you train your model using the MR-NIRP dataset, do you assign the input channel dimension to be 1 (i.e., single NIR channel)? or 3 but with each channel being the same NIR frame?

We appreciate your interest in our work. To maintain the same model structure with RGB input, we duplicate the channel to 3 for the MR-NIRP dataset, just like you described.

**Comment by liteonalvinchuang** [comment]
Thanks!
